### ISSUE TITLE
buildkite status

### ISSUE THREAD

**Issue by davidak** [grahamc/r13y.com#10]
Right now, the README states:

>Right now, this repository builds every date at https://buildkite.com/grahamc/r13y-dot-com/

That's not true. buildkite is broken and build fail

https://buildkite.com/grahamc/r13y-dot-com/

@grahamc what's the plan with buildkite? do you see a chance this could work in the future or should we just remove it?

**Comment by grahamc** [comment]
Just for what it is worth, buildkite is where the checks run. If buildkite is failing, the checks aren't completing.
