### ISSUE TITLE
Website not being updated automatically

### ISSUE THREAD

**Issue by iblech** [grahamc/r13y.com#16]
This is a wonderful project. Thank you very much for it.

Currently it seems that the [website](https://r13y.com/) is not being updated automatically. The footer still says "Generated at 2020-05-10 04:51:34.795219659 UTC", even though https://buildkite.com/grahamc/r13y-dot-com/ reports daily builds.

I'd like to offer my help, but don't really know where to start.

**Comment by JJJollyjim** [comment]
It has been bumped to 2020-07-03, I assume this can be closed :)

**Comment by grahamc** [comment]
Thanks, I didn't even see this issue get opened -- I'm sorry about that. The website should be updating very regularly now :).

**Comment by misuzu** [comment]
Looks like something is broken: https://buildkite.com/grahamc/r13y-dot-com/builds
