### ISSUE TITLE
Why is guile-2.0.13 in the report?

### ISSUE THREAD

**Issue by raboof** [grahamc/r13y.com#18]
`nix why-depends /nix/store/rmx9bqzfgi5mlr0sb9x9zgi047lhy4x3-nixos-minimal-21.03pre56789.gfedcba-x86_64-linux.iso /nix/store/jrnf3bpskbqx3652cw6ir1dq24vmy27x-guile-2.0.13.drv` does not find a link.

`nix-store --query --requisites /nix/store/rmx9bqzfgi5mlr0sb9x9zgi047lhy4x3-nixos-minimal-21.03pre56789.gfedcba-x86_64-linux.iso` does not seem to list any guile path either.

**Comment by grahamc** [comment]
Querying requisites on the result only tells you the run time dependents. This report is in the build closure, ie, on the drv of the iso. The requisites of the drv covers everything from bootstrapping up to the described program.

**Comment by raboof** [comment]
> This report is in the build closure, ie, on the drv of the iso

Aaah, I didn't realize. That makes sense I guess - and means we're a bit further along with making nixpkgs reproducible than I thought :D.
