### ISSUE TITLE
website mentions freenode

### ISSUE THREAD

**Issue by eeeeeta** [grahamc/r13y.com#29]
> There is support for an automatic diff-hook in Nix 2, but it is much more complicated to set up. If you would like to work on this, or need help setting it up, contact *gchristensen on Freenode*. We can work together to write docs on how to use it.

just FYI :)

**Comment by grahamc** [comment]
Thanks! The next generation will have the fix: https://github.com/grahamc/r13y.com/commit/5b3be0e7c1b64cf807fc62187936168f0cc43a3c

**Comment by grahamc** [comment]
I uploaded a fix manually.
