### ISSUE TITLE
update used diffoscope version

### ISSUE THREAD

**Issue by Mindavi** [grahamc/r13y.com#31]
In this line:

https://github.com/grahamc/r13y.com/blob/5b3be0e7c1b64cf807fc62187936168f0cc43a3c/check.sh#L2

I see that nixos-19.09 is used.

I've seen reports mentioning that diffoscope 110 is used, while diffoscope is at version 178 now. Is that due to that line or is that just a red herring?

I can imagine that a newer diffoscope version might give a better overview of where the issue lies with some packages, although it might not matter that much.

Anyhow, I think it would be good to use a somewhat newer version of diffoscope regardless.

**Comment by grahamc** [comment]
I updated to use nixos-unstable-small, so we should be good to go now!
